; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; Zigbee build - ESP-IDF native
[env:esp32-c6-zigbee]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = espidf
monitor_speed = 115200
lib_compat_mode = off

build_flags =
    -D BUS_0_TX_PIN=16
    -D BUS_0_RX_PIN=17
    -D BUS_0_DIR_PIN=23
    -D BUS_0_POW_PIN=18
    -D BUS_0_BUTTON_PIN=1 ; Currently unused

    -D BUS_1_TX_PIN=19
    -D BUS_1_RX_PIN=22
    -D BUS_1_DIR_PIN=21
    -D BUS_1_POW_PIN=20
    -D BUS_1_BUTTON_PIN=2 ; Currently unused

    ; Enable Zigbee support for ESP32-C6
    -D ZIGBEE_MODE_ED
    -D MODE_ZIGBEE_CONTROLLER

board_build.filesystem = littlefs
board_build.partitions = zigbee_zczr.csv

lib_deps =
    bblanchon/ArduinoJson@^7.2.1


; WiFi build - ESP-IDF native
[env:esp32-s3-wifi]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 115200
lib_compat_mode = off

build_flags =
    -D BUS_0_TX_PIN=43
    -D BUS_0_RX_PIN=44
    -D BUS_0_DIR_PIN=6
    -D BUS_0_POW_PIN=9
    -D BUS_0_BUTTON_PIN=2 ; Currently unused

    -D BUS_1_TX_PIN=7
    -D BUS_1_RX_PIN=5
    -D BUS_1_DIR_PIN=4
    -D BUS_1_POW_PIN=8
    -D BUS_1_BUTTON_PIN=3 ; Currently unused

    -D MODE_WIFI_CONTROLLER

board_build.filesystem = littlefs
board_build.partitions = 4mb_inc_ota.csv

lib_deps =
    bblanchon/ArduinoJson@^7.2.1
