; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; WiFi build - ESP-IDF native
[env:esp32-s3-wifi]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 115200
lib_compat_mode = off

build_flags =
    -D BUS_0_TX_PIN=43
    -D BUS_0_RX_PIN=44
    -D BUS_0_DIR_PIN=6
    -D BUS_0_POW_PIN=9

    -D BUS_1_TX_PIN=7
    -D BUS_1_RX_PIN=5
    -D BUS_1_DIR_PIN=4
    -D BUS_1_POW_PIN=8

    -D MODE_WIFI_CONTROLLER

    ; esp_wifi_config library-specific flags
    -D CONFIG_WIFI_CFG_ENABLE_BLE=1
    -D CONFIG_WIFI_CFG_ENABLE_IMPROV_BLE=1
    -D CONFIG_WIFI_CFG_ENABLE_IMPROV_SERIAL=1
    -D CONFIG_WIFI_CFG_ENABLE_WEBUI=1

board_build.filesystem = littlefs
board_build.partitions = 4mb_inc_ota.csv
board_build.sdkconfig_defaults = sdkconfig.defaults

lib_deps =
    bblanchon/ArduinoJson@^7.2.1

